#! /usr/bin/env bash

curl -X GET -H "Content-Type: application/json" -H "Authorization: Bearer `sudo cat ~/.digitalocean-api-token-devbox`" "https://api.digitalocean.com/v2/images?page=1&per_page=100" | python -m json.tool | less
